#!/bin/bash

count=1
while [ $count -le 5 ]; do
    echo "Count: $count"
    sleep 1
    ((count++))
done

EXIT_PLEASE=0
while :
do 
	echo "Press CTRL+Z to stop this loop"
	sleep 1
	if [ $EXIT_PLEASE != 0 ]; then
		break
	fi
done
exit 0
