#!/bin/bash

VAR="My test string"

echo ${VAR:3:4}

# 3 - start with third character
# 4 - determin length that consists of 4 characters
# the result will be "test"

STR="1234567890qwertyuiop"
STR2="abc"
STR3="bcd"
STR4="Bcd"

echo "first character ${STR:0:1}"
echo "last character ${STR: -1}"
echo "first three characters ${STR:0:3}"
echo "forth to six character ${STR: 3: 3}"
echo "third character onwards ${STR: 3}"

if [[ $STR2 < $STR3 ]]; then
	echo "STR2 is less than STR3"
else
	echo "STR3 is greater than STR2"
fi

if [[ $STR3 < $STR4 ]]; then
        echo "STR3 is less than STR4"
else
        echo "STR4 is greater than STR3"
fi
