# This is my test GitHub action, part of a learning prcess

name: My_GitHub_Workflow_Action
env:
  APPLICATION_NAME    : "Test"
  DEPLOY_PACKAGE_NAME : "Test_deploy_version-${{ github.sha }}"
  
on:
  push:
    branches: [ main ]

jobs:
  my_test:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
   
    steps:
      - uses: actions/checkout@v1

      - name: Print Hello World Message in Test
        run: echo "Application name is ${{ env.APPLICATION_NAME }}"
  
  my_deploy:
    runs-on: ${{matrix.os}}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
        needs: [my_test]
    env:
      VAR1 : "This is Variable1"
      VAR2 : "This is Valiable2"
      
    steps:
      - name: Print Environment Variables
        run: |
          echo "Var1 = ${{ env.VAR1 }}" 
          echo "Var2 = ${{ env.VAR2 }}"
          
      - name: Printing Deploy package
        run :
              echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Lets test some packs if they are here (AWS) 
        run : aws --version

